### ISSUE TITLE
Le titre des pages c’est normal ? 

### ISSUE THREAD

**Issue by RomainMarecat** [Nicolasvacher/Projet_EII_Vacher_Just#1]
Paris component 
Welcome component,
Etc c’est bizarre 

Le but c’est pas d’avoir 
Home 
GameList 
GameDetail
Login ?

**Comment by AlexisJust** [comment]
Si, mais on savait pas comment appeler nos pages alors je ‘crois’ qu’on a suivi la docs ionic
